# Generated by Django 4.1.2 on 2023-08-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_member_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
    ]
