# Generated by Django 4.1.2 on 2023-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_remove_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='London', max_length=255),
            preserve_default=False,
        ),
    ]
